import {
  Role,
  RoleDefinition,
  UserPermissions,
  Company,
  Store,
  Terminal,
  User,
  ProductCategory,
  Product,
  Warehouse,
  StockItem,
  Supplier,
  Customer,
  Employee,
  EmployeeShift,
  BankTransaction,
  FiscalSeries,
  ChartOfAccounts,
  AccountPayable,
  AccountReceivable,
  Invoice,
  CashShift,
  SystemEvent,
  PurchaseOrder,
  PurchaseRequisition,
  TimeClockEntry,
  PayrollSlip,
  LeadOpportunity,
  LotBatch,
  OmnichannelOrder,
  InvoiceTemplateConfig,
} from './types';

export const defaultInvoiceTemplates: InvoiceTemplateConfig[] = [
  {
    id: 'tmpl-agro-vendus',
    name: 'Modelo Agro / Vendus MZ (A4)',
    style: 'agro_mz',
    paperSize: 'A4',
    accentColor: '#166534',
    primaryColor: '#166534',
    showLogo: true,
    logoPosition: 'left',
    showWatermark: true,
    watermarkText: 'ORIGINAL',
    showQRCode: true,
    showPaymentInfo: true,
    iban: '000100000119090246657',
    bankIban: '000100000119090246657',
    bankName: 'BIM: Numero de Conta: 1190902466',
    accountNumber: '1190902466',
    swiftBic: 'BIMMMZMA',
    headerNotes: 'FOCO NO AGRO, GANHO NO CAMPO',
    footerNotes: 'Sede: Nampula, 3100, Ribaue. Obrigado pela preferência, volte mais!',
    legalNotice: '(1) Não sujeito; não tributado ou similar',
    fontFamily: 'sans',
    isDefault: true,
  },
  {
    id: 'tmpl-agro-namiconha',
    name: 'Modelo Comercial Namiconha (A4)',
    style: 'agro_mz',
    paperSize: 'A4',
    accentColor: '#c5a47e',
    primaryColor: '#c5a47e',
    showLogo: true,
    logoPosition: 'left',
    showWatermark: true,
    watermarkText: 'ORIGINAL',
    showQRCode: true,
    showPaymentInfo: true,
    iban: '000100000119090246657',
    bankIban: '000100000119090246657',
    bankName: 'Millennium BIM (Moçambique)',
    accountNumber: '1190902466',
    swiftBic: 'BIMMMZMA',
    headerNotes: 'Excelência e Qualidade em Produtos Agrícolas e Comerciais',
    footerNotes: 'Software Certificado nº 0842/ATM. Processado por Sistema Certificado.',
    legalNotice: 'Regime Geral / Isenção Artigo 9º do CIVA Moçambique',
    fontFamily: 'sans',
    isDefault: false,
  },
  {
    id: 'tmpl-modern-mz',
    name: 'Moderno Corporativo MZ (A4)',
    style: 'agro_mz',
    paperSize: 'A4',
    accentColor: '#0284c7',
    primaryColor: '#0284c7',
    showLogo: true,
    logoPosition: 'left',
    showWatermark: false,
    watermarkText: '',
    showQRCode: true,
    showPaymentInfo: true,
    iban: '000100000119090246657',
    bankIban: '000100000119090246657',
    bankName: 'BIM / BCI Moçambique',
    accountNumber: '1190902466',
    swiftBic: 'BIMMMZMA',
    headerNotes: 'Obrigado pela sua preferência comercial.',
    footerNotes: 'Documento processado por computador • Moçambique',
    legalNotice: 'Imposto sobre o Valor Acrescentado (IVA) Discriminado',
    fontFamily: 'sans',
    isDefault: false,
  },
  {
    id: 'tmpl-thermal',
    name: 'Talão Térmico POS (80mm)',
    style: 'thermal',
    paperSize: '80mm',
    accentColor: '#171717',
    primaryColor: '#171717',
    showLogo: true,
    logoPosition: 'center',
    showWatermark: false,
    showQRCode: true,
    showPaymentInfo: false,
    headerNotes: 'Talão de Venda a Balcão / POS',
    footerNotes: 'Conserve este talão. Obrigado pela sua visita!',
    legalNotice: 'Fatura Simplificada emitida nos termos da Legislação Fiscal em vigor.',
    fontFamily: 'mono',
    isDefault: false,
  },
];

export const initialCompanies: Company[] = [
  {
    id: 'comp-mz-1',
    name: 'AgroEco Jaro Moçambique, Lda.',
    tradeName: 'AgroEco Jaro',
    taxNumber: '400982341', // NUIT Moçambique
    address: 'Avenida 24 de Julho, 1890, R/C',
    city: 'Maputo',
    postalCode: '1100',
    country: 'Moçambique',
    currency: 'MZN',
    currencySymbol: 'Mt',
    currencyPosition: 'suffix',
    currencyDecimals: 2,
    phone: '+258 84 123 4567',
    email: 'agroecojaro.lda@gmail.com',
    website: 'https://agroecojaro.co.mz',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=300&auto=format&fit=crop&q=80',
    softwareCertNumber: '0842/ATM',
    saftVersion: '1.04_01',
    shareCapital: '2.500.000,00 Mt',
    commercialRegistryNumber: '400982341 - Conservatória de Maputo',
    defaultIban: 'MZ59 0001 0000 1234 5678 9012 3',
    defaultBank: 'Millennium BIM (Moçambique)',
    activeInvoiceTemplateId: 'tmpl-agro-vendus',
    invoiceTemplates: defaultInvoiceTemplates,
  },
  {
    id: 'comp-1',
    name: 'OmniRetail SGPS S.A.',
    tradeName: 'OmniRetail Group',
    taxNumber: '509823410',
    address: 'Avenida da Liberdade, 245, 4º',
    city: 'Lisboa',
    postalCode: '1250-143',
    country: 'Portugal',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'suffix',
    currencyDecimals: 2,
    phone: '+351 210 987 650',
    email: 'geral@omniretail.pt',
    website: 'https://omniretail.pt',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=300&auto=format&fit=crop&q=80',
    softwareCertNumber: '4120/AT',
    saftVersion: '1.04_01',
    shareCapital: '150.000,00 €',
    commercialRegistryNumber: '509823410 - CRC Lisboa',
    defaultIban: 'PT50 0033 0000 4523 8912 0010 4',
    defaultBank: 'Banco Millennium BCP',
    activeInvoiceTemplateId: 'tmpl-agro-vendus',
    invoiceTemplates: defaultInvoiceTemplates,
  },
  {
    id: 'comp-2',
    name: 'TechGlobal Lusitana Lda',
    tradeName: 'TechStore Iberia',
    taxNumber: '512398471',
    address: 'Rua de Santa Catarina, 890',
    city: 'Porto',
    postalCode: '4000-447',
    country: 'Portugal',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'suffix',
    currencyDecimals: 2,
    phone: '+351 220 112 334',
    email: 'contacto@techglobal.pt',
    website: 'https://techglobal.pt',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
    softwareCertNumber: '4890/AT',
    saftVersion: '1.04_01',
    shareCapital: '50.000,00 €',
    commercialRegistryNumber: '512398471 - CRC Porto',
    defaultIban: 'PT50 0018 0000 9876 5432 1012 3',
    defaultBank: 'Banco Santander Totta',
    activeInvoiceTemplateId: 'tmpl-agro-vendus',
    invoiceTemplates: defaultInvoiceTemplates,
  },
];

export const initialStores: Store[] = [
  {
    id: 'store-lis-1',
    companyId: 'comp-1',
    code: 'LIS-01',
    name: 'OmniRetail Lisboa Baixa',
    address: 'Rua Augusta, 142',
    city: 'Lisboa',
    phone: '+351 213 445 566',
    managerId: 'usr-gerente',
    defaultWarehouseId: 'wh-lis-store',
    terminalsCount: 3,
  },
  {
    id: 'store-por-2',
    companyId: 'comp-1',
    code: 'POR-02',
    name: 'OmniRetail Porto Shopping',
    address: 'Av. dos Aliados, 75',
    city: 'Porto',
    phone: '+351 223 998 877',
    managerId: 'usr-gerente-2',
    defaultWarehouseId: 'wh-por-store',
    terminalsCount: 2,
  },
  {
    id: 'store-coi-3',
    companyId: 'comp-1',
    code: 'COI-03',
    name: 'OmniRetail Coimbra Retail',
    address: 'Largo da Portagem, 12',
    city: 'Coimbra',
    phone: '+351 239 123 456',
    managerId: 'usr-gerente-3',
    defaultWarehouseId: 'wh-coi-store',
    terminalsCount: 1,
  },
];

export const initialTerminals: Terminal[] = [
  {
    id: 'term-lis-1',
    storeId: 'store-lis-1',
    code: 'POS-01',
    description: 'Caixa Rápido Entrada',
    isActive: true,
    currentShiftId: 'shift-1',
    printerModel: 'Epson TM-T88VI Thermal 80mm',
  },
  {
    id: 'term-lis-2',
    storeId: 'store-lis-1',
    code: 'POS-02',
    description: 'Caixa Principal Balcão',
    isActive: true,
    currentShiftId: null,
    printerModel: 'Epson TM-T88VI Thermal 80mm',
  },
  {
    id: 'term-por-1',
    storeId: 'store-por-2',
    code: 'POS-01',
    description: 'Caixa 1 Piso Térreo',
    isActive: true,
    currentShiftId: null,
    printerModel: 'Star Micronics TSP143III',
  },
];

export { initialSales } from './data/mockSales';

export const defaultPermissionsByRole: Record<Role, UserPermissions> = {
  admin: {
    pos: { read: true, create: true, edit: true, delete: true, fiscal: true },
    documents: { read: true, create: true, edit: true, delete: true, fiscal: true },
    stores: { read: true, create: true, edit: true, delete: true, fiscal: true },
    stock: { read: true, create: true, edit: true, delete: true, fiscal: true },
    finance: { read: true, create: true, edit: true, delete: true, fiscal: true },
    hr: { read: true, create: true, edit: true, delete: true, fiscal: true },
    procurement: { read: true, create: true, edit: true, delete: true, fiscal: true },
    crm: { read: true, create: true, edit: true, delete: true, fiscal: true },
    orders: { read: true, create: true, edit: true, delete: true, fiscal: true },
    events: { read: true, create: true, edit: true, delete: true, fiscal: true },
    settings: { read: true, create: true, edit: true, delete: true, fiscal: true },
    users: { read: true, create: true, edit: true, delete: true, fiscal: true },
    analytics: { read: true, create: true, edit: true, delete: true, fiscal: true },
  },
  gerente: {
    pos: { read: true, create: true, edit: true, delete: true, fiscal: true },
    documents: { read: true, create: true, edit: true, delete: true, fiscal: true },
    stores: { read: true, create: true, edit: true, delete: false, fiscal: true },
    stock: { read: true, create: true, edit: true, delete: true, fiscal: false },
    finance: { read: true, create: true, edit: true, delete: false, fiscal: true },
    hr: { read: true, create: true, edit: true, delete: false, fiscal: false },
    procurement: { read: true, create: true, edit: true, delete: false, fiscal: false },
    crm: { read: true, create: true, edit: true, delete: true, fiscal: false },
    orders: { read: true, create: true, edit: true, delete: true, fiscal: false },
    events: { read: true, create: true, edit: false, delete: false, fiscal: false },
    settings: { read: true, create: true, edit: true, delete: false, fiscal: true },
    users: { read: true, create: true, edit: true, delete: false, fiscal: false },
    analytics: { read: true, create: true, edit: true, delete: false, fiscal: true },
  },
  caixa: {
    pos: { read: true, create: true, edit: false, delete: false, fiscal: true },
    documents: { read: true, create: true, edit: false, delete: false, fiscal: true },
    stores: { read: false, create: false, edit: false, delete: false, fiscal: false },
    stock: { read: true, create: false, edit: false, delete: false, fiscal: false },
    finance: { read: false, create: false, edit: false, delete: false, fiscal: false },
    hr: { read: false, create: false, edit: false, delete: false, fiscal: false },
    procurement: { read: false, create: false, edit: false, delete: false, fiscal: false },
    crm: { read: true, create: true, edit: false, delete: false, fiscal: false },
    orders: { read: true, create: true, edit: true, delete: false, fiscal: false },
    events: { read: false, create: false, edit: false, delete: false, fiscal: false },
    settings: { read: false, create: false, edit: false, delete: false, fiscal: false },
    users: { read: false, create: false, edit: false, delete: false, fiscal: false },
    analytics: { read: true, create: false, edit: false, delete: false, fiscal: false },
  },
  financeiro: {
    pos: { read: true, create: false, edit: false, delete: false, fiscal: true },
    documents: { read: true, create: true, edit: true, delete: true, fiscal: true },
    stores: { read: true, create: false, edit: false, delete: false, fiscal: false },
    stock: { read: true, create: false, edit: false, delete: false, fiscal: false },
    finance: { read: true, create: true, edit: true, delete: true, fiscal: true },
    hr: { read: true, create: false, edit: false, delete: false, fiscal: false },
    procurement: { read: true, create: true, edit: true, delete: false, fiscal: false },
    crm: { read: true, create: false, edit: false, delete: false, fiscal: false },
    orders: { read: true, create: false, edit: false, delete: false, fiscal: false },
    events: { read: true, create: false, edit: false, delete: false, fiscal: false },
    settings: { read: true, create: false, edit: false, delete: false, fiscal: true },
    users: { read: false, create: false, edit: false, delete: false, fiscal: false },
    analytics: { read: true, create: true, edit: true, delete: true, fiscal: true },
  },
  rh: {
    pos: { read: false, create: false, edit: false, delete: false, fiscal: false },
    documents: { read: false, create: false, edit: false, delete: false, fiscal: false },
    stores: { read: false, create: false, edit: false, delete: false, fiscal: false },
    stock: { read: false, create: false, edit: false, delete: false, fiscal: false },
    finance: { read: false, create: false, edit: false, delete: false, fiscal: false },
    hr: { read: true, create: true, edit: true, delete: true, fiscal: false },
    procurement: { read: false, create: false, edit: false, delete: false, fiscal: false },
    crm: { read: false, create: false, edit: false, delete: false, fiscal: false },
    orders: { read: false, create: false, edit: false, delete: false, fiscal: false },
    events: { read: false, create: false, edit: false, delete: false, fiscal: false },
    settings: { read: false, create: false, edit: false, delete: false, fiscal: false },
    users: { read: true, create: false, edit: false, delete: false, fiscal: false },
    analytics: { read: false, create: false, edit: false, delete: false, fiscal: false },
  },
  comprador: {
    pos: { read: false, create: false, edit: false, delete: false, fiscal: false },
    documents: { read: true, create: false, edit: false, delete: false, fiscal: false },
    stores: { read: false, create: false, edit: false, delete: false, fiscal: false },
    stock: { read: true, create: true, edit: true, delete: false, fiscal: false },
    finance: { read: true, create: false, edit: false, delete: false, fiscal: false },
    hr: { read: false, create: false, edit: false, delete: false, fiscal: false },
    procurement: { read: true, create: true, edit: true, delete: true, fiscal: false },
    crm: { read: false, create: false, edit: false, delete: false, fiscal: false },
    orders: { read: true, create: false, edit: false, delete: false, fiscal: false },
    events: { read: false, create: false, edit: false, delete: false, fiscal: false },
    settings: { read: false, create: false, edit: false, delete: false, fiscal: false },
    users: { read: false, create: false, edit: false, delete: false, fiscal: false },
    analytics: { read: true, create: false, edit: false, delete: false, fiscal: false },
  },
};

export const initialRoles: RoleDefinition[] = [
  {
    id: 'admin',
    name: 'Administrador Geral',
    description: 'Acesso total a todos os módulos, parametrizações fiscais AT e gestão global de utilizadores',
    badge: 'ADMIN',
    color: 'border-red-500/30 text-red-400 bg-red-500/10',
    permissions: defaultPermissionsByRole.admin,
  },
  {
    id: 'gerente',
    name: 'Gerente de Loja',
    description: 'Gestão operacional de loja, supervisão de caixa, stocks, inventário e relatórios de vendas',
    badge: 'GERENTE',
    color: 'border-amber-500/30 text-amber-400 bg-amber-500/10',
    permissions: defaultPermissionsByRole.gerente,
  },
  {
    id: 'caixa',
    name: 'Operador de Caixa (POS)',
    description: 'Operações de caixa, emissão de faturas simplificadas, abertura/fecho de turno e fidelização',
    badge: 'POS / CAIXA',
    color: 'border-emerald-500/30 text-emerald-400 bg-emerald-500/10',
    permissions: defaultPermissionsByRole.caixa,
  },
  {
    id: 'financeiro',
    name: 'Responsável Financeiro & Contabilista',
    description: 'Contabilidade, tesouraria, reconciliação bancária, apuramento de IVA e exportação SAF-T (PT)',
    badge: 'FINANCEIRO',
    color: 'border-blue-500/30 text-blue-400 bg-blue-500/10',
    permissions: defaultPermissionsByRole.financeiro,
  },
  {
    id: 'rh',
    name: 'Recursos Humanos',
    description: 'Gestão de colaboradores, assiduidade, controlo de turnos e processamento de salários',
    badge: 'RECURSOS HUMANOS',
    color: 'border-purple-500/30 text-purple-400 bg-purple-500/10',
    permissions: defaultPermissionsByRole.rh,
  },
  {
    id: 'comprador',
    name: 'Gestor de Compras & Procurement',
    description: 'Gestão de fornecedores, requisições de compra, ordens de encomenda e receção de mercadorias',
    badge: 'COMPRAS',
    color: 'border-cyan-500/30 text-cyan-400 bg-cyan-500/10',
    permissions: defaultPermissionsByRole.comprador,
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-admin',
    name: 'Dra. Sofia Martins',
    username: 'sofia.martins',
    email: 'sofia.martins@omniretail.pt',
    role: 'admin',
    storeId: 'store-lis-1',
    companyId: 'comp-1',
    pin: '1234',
    phone: '+351 919 887 766',
    isActive: true,
    createdAt: '2025-01-10',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    permissions: defaultPermissionsByRole.admin,
  },
  {
    id: 'usr-caixa',
    name: 'Gonçalo Ribeiro',
    username: 'goncalo.ribeiro',
    email: 'goncalo.ribeiro@omniretail.pt',
    role: 'caixa',
    storeId: 'store-lis-1',
    companyId: 'comp-1',
    pin: '1111',
    phone: '+351 912 334 455',
    isActive: true,
    createdAt: '2025-03-15',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    permissions: defaultPermissionsByRole.caixa,
  },
  {
    id: 'usr-gerente',
    name: 'Manuel Fernandes',
    username: 'manuel.fernandes',
    email: 'manuel.fernandes@omniretail.pt',
    role: 'gerente',
    storeId: 'store-lis-1',
    companyId: 'comp-1',
    pin: '2222',
    phone: '+351 925 667 788',
    isActive: true,
    createdAt: '2025-02-01',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    permissions: defaultPermissionsByRole.gerente,
  },
  {
    id: 'usr-fin',
    name: 'Ana Beatriz Ramos',
    username: 'ana.ramos',
    email: 'ana.ramos@omniretail.pt',
    role: 'financeiro',
    storeId: 'store-lis-1',
    companyId: 'comp-1',
    pin: '3333',
    phone: '+351 933 445 566',
    isActive: true,
    createdAt: '2025-02-20',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    permissions: defaultPermissionsByRole.financeiro,
  },
  {
    id: 'usr-rh',
    name: 'Clara Vasconcelos',
    username: 'clara.vasconcelos',
    email: 'clara.vasconcelos@omniretail.pt',
    role: 'rh',
    storeId: 'store-lis-1',
    companyId: 'comp-1',
    pin: '4444',
    phone: '+351 961 223 344',
    isActive: true,
    createdAt: '2025-04-05',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    permissions: defaultPermissionsByRole.rh,
  },
  {
    id: 'usr-compras',
    name: 'Pedro Alentejano',
    username: 'pedro.alentejano',
    email: 'pedro.compras@omniretail.pt',
    role: 'comprador',
    storeId: 'store-lis-1',
    companyId: 'comp-1',
    pin: '5555',
    phone: '+351 918 776 655',
    isActive: true,
    createdAt: '2025-05-12',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    permissions: defaultPermissionsByRole.comprador,
  },
];

export const initialFiscalSeries: FiscalSeries[] = [
  {
    id: 'ser-2026a',
    companyId: 'comp-1',
    code: '2026A',
    description: 'Série Principal de Faturação Geral 2026',
    documentType: 'TODOS',
    currentSequence: 142,
    isActive: true,
    atValidationCode: 'AT-VAL-98234-A',
    startingDate: '2026-01-01',
  },
  {
    id: 'ser-pos1',
    companyId: 'comp-1',
    code: 'POS1',
    description: 'Série Balcão Lisboa Baixa (Faturas Simplificadas)',
    documentType: 'FS',
    currentSequence: 589,
    isActive: true,
    atValidationCode: 'AT-VAL-98234-POS1',
    startingDate: '2026-01-01',
  },
  {
    id: 'ser-pos2',
    companyId: 'comp-1',
    code: 'POS2',
    description: 'Série Balcão Porto Shopping',
    documentType: 'FS',
    currentSequence: 312,
    isActive: true,
    atValidationCode: 'AT-VAL-98234-POS2',
    startingDate: '2026-01-01',
  },
  {
    id: 'ser-nc',
    companyId: 'comp-1',
    code: 'NC26',
    description: 'Série de Notas de Crédito e Retificações',
    documentType: 'NC',
    currentSequence: 18,
    isActive: true,
    atValidationCode: 'AT-VAL-98234-NC',
    startingDate: '2026-01-01',
  },
];

export const initialCategories: ProductCategory[] = [
  { id: 'cat-bebidas', name: 'Bebidas & Cafés', color: 'emerald' },
  { id: 'cat-alimentar', name: 'Alimentação & Snacks', color: 'amber' },
  { id: 'cat-tech', name: 'Tecnologia & Acessórios', color: 'blue' },
  { id: 'cat-vestuario', name: 'Vestuário & Têxtil', color: 'violet' },
  { id: 'cat-higiene', name: 'Higiene & Bem-Estar', color: 'teal' },
  { id: 'cat-papelaria', name: 'Papelaria & Escritório', color: 'rose' },
];

export const initialWarehouses: Warehouse[] = [
  {
    id: 'wh-central',
    companyId: 'comp-1',
    name: 'Armazém Central Logística (Alverca)',
    code: 'WH-CENTRAL',
    location: 'Estrada Nacional 10, Alverca',
    isDefault: true,
  },
  {
    id: 'wh-lis-store',
    companyId: 'comp-1',
    storeId: 'store-lis-1',
    name: 'Armazém Loja Lisboa Baixa',
    code: 'WH-LIS-01',
    location: 'Rua Augusta, Cave 1',
    isDefault: false,
  },
  {
    id: 'wh-por-store',
    companyId: 'comp-1',
    storeId: 'store-por-2',
    name: 'Armazém Loja Porto',
    code: 'WH-POR-02',
    location: 'Av. Aliados, Armazém B',
    isDefault: false,
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    companyId: 'comp-1',
    sku: 'BEB-001',
    barcode: '5601234567890',
    name: 'Café Espresso Gourmet 250g',
    category: 'cat-bebidas',
    price: 4.85,
    costPrice: 2.20,
    taxRate: 13,
    unit: 'un',
    minStock: 20,
    maxStock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: true,
    supplierId: 'sup-1',
    description: 'Lote selecionado 100% Arábica Torra Média',
  },
  {
    id: 'prod-2',
    companyId: 'comp-1',
    sku: 'BEB-002',
    barcode: '5601234567891',
    name: 'Água Mineral das Pedras 6x25cl',
    category: 'cat-bebidas',
    price: 3.49,
    costPrice: 1.65,
    taxRate: 6,
    unit: 'cx',
    minStock: 30,
    maxStock: 300,
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: true,
    supplierId: 'sup-1',
    description: 'Pack de 6 garrafas de vidro com gás natural',
  },
  {
    id: 'prod-3',
    companyId: 'comp-1',
    sku: 'ALI-001',
    barcode: '5601234567892',
    name: 'Azeite Virgem Extra DOP 750ml',
    category: 'cat-alimentar',
    price: 8.90,
    costPrice: 5.10,
    taxRate: 6,
    unit: 'un',
    minStock: 15,
    maxStock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: true,
    supplierId: 'sup-2',
    description: 'Acidez máxima 0.2% Trás-os-Montes',
  },
  {
    id: 'prod-4',
    companyId: 'comp-1',
    sku: 'ALI-002',
    barcode: '5601234567893',
    name: 'Queijo da Serra Curado 500g',
    category: 'cat-alimentar',
    price: 12.50,
    costPrice: 7.20,
    taxRate: 6,
    unit: 'un',
    minStock: 10,
    maxStock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: true,
    supplierId: 'sup-2',
    description: 'Leite cru de ovelha bordaleira',
  },
  {
    id: 'prod-5',
    companyId: 'comp-1',
    sku: 'TEC-001',
    barcode: '5601234567894',
    name: 'Auriculares Bluetooth Pro ANC',
    category: 'cat-tech',
    price: 49.99,
    costPrice: 21.50,
    taxRate: 23,
    unit: 'un',
    minStock: 8,
    maxStock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: false,
    supplierId: 'sup-3',
    description: 'Cancelamento de ruído ativo 32h autonomia',
  },
  {
    id: 'prod-6',
    companyId: 'comp-1',
    sku: 'TEC-002',
    barcode: '5601234567895',
    name: 'Cabo USB-C Rápido 100W 2m Trançado',
    category: 'cat-tech',
    price: 14.95,
    costPrice: 4.80,
    taxRate: 23,
    unit: 'un',
    minStock: 25,
    maxStock: 150,
    imageUrl: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: false,
    supplierId: 'sup-3',
    description: 'Carregamento ultra-rápido PD 3.0 em nylon',
  },
  {
    id: 'prod-7',
    companyId: 'comp-1',
    sku: 'VES-001',
    barcode: '5601234567896',
    name: 'T-Shirt Algodão Orgânico Premium',
    category: 'cat-vestuario',
    price: 19.90,
    costPrice: 6.50,
    taxRate: 23,
    unit: 'un',
    minStock: 12,
    maxStock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: false,
    supplierId: 'sup-4',
    description: '100% Algodão biológico unissexo',
  },
  {
    id: 'prod-8',
    companyId: 'comp-1',
    sku: 'PAP-001',
    barcode: '5601234567897',
    name: 'Caderno Moleskine Executive A5',
    category: 'cat-papelaria',
    price: 16.50,
    costPrice: 7.90,
    taxRate: 23,
    unit: 'un',
    minStock: 15,
    maxStock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&auto=format&fit=crop&q=80',
    hasBatchControl: false,
    supplierId: 'sup-4',
    description: 'Capa dura preta pautado 192 páginas',
  },
];

export const initialStock: StockItem[] = [
  { id: 'stk-1', productId: 'prod-1', warehouseId: 'wh-lis-store', quantity: 48, reserved: 2, avgCost: 2.20, batchNumber: 'LOT-2026-CF1', expiryDate: '2027-08-01' },
  { id: 'stk-2', productId: 'prod-1', warehouseId: 'wh-central', quantity: 180, reserved: 0, avgCost: 2.15, batchNumber: 'LOT-2026-CF1', expiryDate: '2027-08-01' },
  { id: 'stk-3', productId: 'prod-2', warehouseId: 'wh-lis-store', quantity: 94, reserved: 0, avgCost: 1.65, batchNumber: 'LOT-2026-AG2', expiryDate: '2028-01-15' },
  { id: 'stk-4', productId: 'prod-3', warehouseId: 'wh-lis-store', quantity: 32, reserved: 0, avgCost: 5.10, batchNumber: 'LOT-2026-AZ1', expiryDate: '2027-12-31' },
  { id: 'stk-5', productId: 'prod-4', warehouseId: 'wh-lis-store', quantity: 6, reserved: 1, avgCost: 7.20, batchNumber: 'LOT-2026-QJ5', expiryDate: '2026-11-20' }, // Low stock!
  { id: 'stk-6', productId: 'prod-5', warehouseId: 'wh-lis-store', quantity: 18, reserved: 0, avgCost: 21.50 },
  { id: 'stk-7', productId: 'prod-6', warehouseId: 'wh-lis-store', quantity: 55, reserved: 0, avgCost: 4.80 },
  { id: 'stk-8', productId: 'prod-7', warehouseId: 'wh-lis-store', quantity: 24, reserved: 0, avgCost: 6.50 },
  { id: 'stk-9', productId: 'prod-8', warehouseId: 'wh-lis-store', quantity: 30, reserved: 0, avgCost: 7.90 },
];

export const initialLots: LotBatch[] = [
  {
    id: 'lot-1',
    productId: 'prod-1',
    warehouseId: 'wh-lis-store',
    batchNumber: 'LOT-2026-CF1',
    manufacturingDate: '2026-06-10',
    expiryDate: '2027-08-01',
    initialQuantity: 100,
    currentQuantity: 48,
    supplierId: 'sup-1',
  },
  {
    id: 'lot-2',
    productId: 'prod-4',
    warehouseId: 'wh-lis-store',
    batchNumber: 'LOT-2026-QJ5',
    manufacturingDate: '2026-07-01',
    expiryDate: '2026-11-20',
    initialQuantity: 30,
    currentQuantity: 6,
    supplierId: 'sup-2',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    companyId: 'comp-1',
    code: 'FOR-001',
    name: 'Delta Cafés & Bebidas de Portugal S.A.',
    tradeName: 'Grupo Nabeiro Delta',
    taxNumber: '501234987',
    email: 'encomendas@delta-cafes.pt',
    phone: '+351 268 680 000',
    address: 'Avenida Calouste Gulbenkian, Campo Maior',
    paymentTerms: '30 dias',
    iban: 'PT50 0033 0000 4523 8912 0014 5',
    rating: 5,
    categories: ['Bebidas', 'Cafés'],
  },
  {
    id: 'sup-2',
    companyId: 'comp-1',
    code: 'FOR-002',
    name: 'Cooperativa Agrícola das Beiras CRL',
    tradeName: 'AgroBeiras',
    taxNumber: '504891230',
    email: 'vendas@agrobeiras.pt',
    phone: '+351 275 412 890',
    address: 'Zona Industrial do Fundão, Lote 14',
    paymentTerms: '45 dias',
    iban: 'PT50 0035 0120 7894 5612 3001 2',
    rating: 4,
    categories: ['Alimentação', 'Azeites', 'Queijos'],
  },
  {
    id: 'sup-3',
    companyId: 'comp-1',
    code: 'FOR-003',
    name: 'TechDistribuição Ibérica S.A.',
    tradeName: 'TechDistro',
    taxNumber: '508912345',
    email: 'b2b@techdistro.pt',
    phone: '+351 219 887 766',
    address: 'Parque de Ciência e Tecnologia, Sintra',
    paymentTerms: '60 dias',
    iban: 'PT50 0018 0002 9845 6123 0021 9',
    rating: 5,
    categories: ['Tecnologia', 'Eletrónica'],
  },
  {
    id: 'sup-4',
    companyId: 'comp-1',
    code: 'FOR-004',
    name: 'LusoTextil & Papelaria Global Lda',
    tradeName: 'LusoTextil',
    taxNumber: '506781290',
    email: 'contacto@lusotextil.pt',
    phone: '+351 253 456 789',
    address: 'Rua dos Têxteis, Guimarães',
    paymentTerms: '30 dias',
    iban: 'PT50 0007 0045 1289 7456 0012 3',
    rating: 4,
    categories: ['Vestuário', 'Papelaria'],
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    companyId: 'comp-1',
    name: 'Consumidor Final',
    taxNumber: '999999990',
    email: 'consumidor@anonimo.pt',
    phone: '',
    address: 'Balcão de Venda',
    city: 'Lisboa',
    postalCode: '1000-001',
    segment: 'recorrente',
    loyaltyPoints: 0,
    loyaltyTier: 'Bronze',
    totalSpent: 12450.80,
    ordersCount: 312,
    creditLimit: 0,
    currentCredit: 0,
    createdAt: '2026-01-01',
  },
  {
    id: 'cust-2',
    companyId: 'comp-1',
    name: 'João Pedro Carvalho',
    taxNumber: '234567890',
    email: 'joao.carvalho@empresa.pt',
    phone: '+351 912 345 678',
    address: 'Rua Castilho, 50, 2º Dir',
    city: 'Lisboa',
    postalCode: '1250-071',
    segment: 'vip',
    loyaltyPoints: 480,
    loyaltyTier: 'Ouro',
    totalSpent: 2890.40,
    ordersCount: 42,
    creditLimit: 1500,
    currentCredit: 0,
    createdAt: '2026-02-14',
  },
  {
    id: 'cust-3',
    companyId: 'comp-1',
    name: 'Maria Inês Ferreira',
    taxNumber: '256789123',
    email: 'ines.ferreira@gmail.com',
    phone: '+351 934 567 890',
    address: 'Av. da Boavista, 1200',
    city: 'Porto',
    postalCode: '4100-132',
    segment: 'recorrente',
    loyaltyPoints: 195,
    loyaltyTier: 'Prata',
    totalSpent: 940.15,
    ordersCount: 18,
    creditLimit: 500,
    currentCredit: 0,
    createdAt: '2026-03-02',
  },
  {
    id: 'cust-4',
    companyId: 'comp-1',
    name: 'Arquitetos & Associados Lda',
    taxNumber: '509123888',
    email: 'compras@arqassociados.pt',
    phone: '+351 213 890 123',
    address: 'Largo do Rato, 8, 3º',
    city: 'Lisboa',
    postalCode: '1250-186',
    segment: 'vip',
    loyaltyPoints: 920,
    loyaltyTier: 'Platina',
    totalSpent: 8450.00,
    ordersCount: 15,
    creditLimit: 5000,
    currentCredit: 1240.00,
    createdAt: '2026-01-10',
  },
  {
    id: 'cust-5',
    companyId: 'comp-1',
    name: 'Tiago Miguel Neves',
    taxNumber: '219874563',
    email: 'tiago.neves@outlook.pt',
    phone: '+351 961 234 567',
    address: 'Rua do Ouro, 15',
    city: 'Coimbra',
    postalCode: '3000-001',
    segment: 'em_risco',
    loyaltyPoints: 40,
    loyaltyTier: 'Bronze',
    totalSpent: 185.00,
    ordersCount: 3,
    creditLimit: 0,
    currentCredit: 0,
    createdAt: '2026-04-18',
  },
];

export const initialChartOfAccounts: ChartOfAccounts[] = [
  { code: '11', name: 'Caixa', type: 'ativo', level: 1 },
  { code: '11.1', name: 'Caixa Principal Lisboa', type: 'ativo', level: 2, parentCode: '11' },
  { code: '11.2', name: 'Caixa POS-01', type: 'ativo', level: 2, parentCode: '11' },
  { code: '12', name: 'Depósitos à Ordem (Bancos)', type: 'ativo', level: 1 },
  { code: '12.1', name: 'Banco Comercial Português (Millennium BCP)', type: 'ativo', level: 2, parentCode: '12' },
  { code: '12.2', name: 'Caixa Geral de Depósitos', type: 'ativo', level: 2, parentCode: '12' },
  { code: '21', name: 'Clientes', type: 'ativo', level: 1 },
  { code: '21.1', name: 'Clientes Conta Corrente', type: 'ativo', level: 2, parentCode: '21' },
  { code: '22', name: 'Fornecedores', type: 'passivo', level: 1 },
  { code: '22.1', name: 'Fornecedores Conta Corrente', type: 'passivo', level: 2, parentCode: '22' },
  { code: '24', name: 'Estado e Outros Entes Públicos', type: 'passivo', level: 1 },
  { code: '24.3', name: 'IVA Liquidado (Vendas)', type: 'passivo', level: 2, parentCode: '24' },
  { code: '24.2', name: 'IVA Dedutível (Compras)', type: 'ativo', level: 2, parentCode: '24' },
  { code: '31', name: 'Compras', type: 'gasto', level: 1 },
  { code: '31.1', name: 'Compras de Mercadorias', type: 'gasto', level: 2, parentCode: '31' },
  { code: '61', name: 'Custo das Mercadorias Vendidas (CMVMC)', type: 'gasto', level: 1 },
  { code: '62', name: 'Fornecimentos e Serviços Externos (FSE)', type: 'gasto', level: 1 },
  { code: '63', name: 'Gastos com o Pessoal', type: 'gasto', level: 1 },
  { code: '63.1', name: 'Remunerações dos Órgãos Sociais e Pessoal', type: 'gasto', level: 2, parentCode: '63' },
  { code: '71', name: 'Vendas', type: 'rendimento', level: 1 },
  { code: '71.1', name: 'Vendas de Mercadorias (Taxa Normal 23%)', type: 'rendimento', level: 2, parentCode: '71' },
  { code: '71.2', name: 'Vendas de Mercadorias (Taxa Intermédia 13%)', type: 'rendimento', level: 2, parentCode: '71' },
  { code: '71.3', name: 'Vendas de Mercadorias (Taxa Reduzida 6%)', type: 'rendimento', level: 2, parentCode: '71' },
];

export const initialAccountsPayable: AccountPayable[] = [
  {
    id: 'ap-1',
    companyId: 'comp-1',
    supplierId: 'sup-1',
    supplierName: 'Delta Cafés & Bebidas de Portugal S.A.',
    documentNumber: 'FT-DEL-2026/8942',
    date: '2026-08-01',
    dueDate: '2026-08-31',
    amount: 1450.00,
    paidAmount: 0,
    status: 'pendente',
    notes: 'Lote de Café Espresso e Açúcar Saquetas',
  },
  {
    id: 'ap-2',
    companyId: 'comp-1',
    supplierId: 'sup-3',
    supplierName: 'TechDistribuição Ibérica S.A.',
    documentNumber: 'FT-TEC-2026/0419',
    date: '2026-07-15',
    dueDate: '2026-08-15',
    amount: 2890.50,
    paidAmount: 0,
    status: 'vencido',
    notes: 'Fatura de fones bluetooth e cabos USB-C',
  },
  {
    id: 'ap-3',
    companyId: 'comp-1',
    supplierId: 'sup-2',
    supplierName: 'Cooperativa Agrícola das Beiras CRL',
    documentNumber: 'FT-AGR-2026/1102',
    date: '2026-08-10',
    dueDate: '2026-09-25',
    amount: 870.00,
    paidAmount: 870.00,
    status: 'pago',
    paymentDate: '2026-08-12',
    paymentMethod: 'transferencia',
    notes: 'Azeite Virgem Extra e Queijos Serra',
  },
];

export const initialAccountsReceivable: AccountReceivable[] = [
  {
    id: 'ar-1',
    companyId: 'comp-1',
    customerId: 'cust-4',
    customerName: 'Arquitetos & Associados Lda',
    documentNumber: 'FT 2026A/00140',
    date: '2026-08-05',
    dueDate: '2026-09-05',
    amount: 1240.00,
    receivedAmount: 0,
    status: 'pendente',
  },
  {
    id: 'ar-2',
    companyId: 'comp-1',
    customerId: 'cust-2',
    customerName: 'João Pedro Carvalho',
    documentNumber: 'FT 2026A/00138',
    date: '2026-07-20',
    dueDate: '2026-08-20',
    amount: 345.00,
    receivedAmount: 345.00,
    status: 'pago',
    receiptDate: '2026-08-18',
  },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    companyId: 'comp-1',
    code: 'EMP-001',
    name: 'Gonçalo Ribeiro',
    role: 'Operador de Caixa Senior',
    department: 'Operações de Loja',
    storeId: 'store-lis-1',
    taxNumber: '249871230',
    socialSecurityNumber: '11894561230',
    email: 'goncalo.ribeiro@omniretail.pt',
    phone: '+351 912 888 111',
    baseSalary: 1100.00,
    mealAllowanceDaily: 9.60,
    contractType: 'sem_termo',
    admissionDate: '2024-03-01',
    status: 'ativo',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-2',
    companyId: 'comp-1',
    code: 'EMP-002',
    name: 'Manuel Fernandes',
    role: 'Gerente de Loja Lisboa',
    department: 'Gestão de Loja',
    storeId: 'store-lis-1',
    taxNumber: '210984561',
    socialSecurityNumber: '11098451299',
    email: 'manuel.fernandes@omniretail.pt',
    phone: '+351 963 222 333',
    baseSalary: 1850.00,
    mealAllowanceDaily: 9.60,
    contractType: 'sem_termo',
    admissionDate: '2022-09-15',
    status: 'ativo',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-3',
    companyId: 'comp-1',
    code: 'EMP-003',
    name: 'Ana Beatriz Ramos',
    role: 'Diretora Financeira & Contabilidade',
    department: 'Financeiro',
    storeId: 'store-lis-1',
    taxNumber: '254129870',
    socialSecurityNumber: '11984521094',
    email: 'ana.ramos@omniretail.pt',
    phone: '+351 934 112 445',
    baseSalary: 2400.00,
    mealAllowanceDaily: 9.60,
    contractType: 'sem_termo',
    admissionDate: '2021-05-01',
    status: 'ativo',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-4',
    companyId: 'comp-1',
    code: 'EMP-004',
    name: 'Pedro Alentejano',
    role: 'Gestor de Compras e Stock',
    department: 'Procurement & Logística',
    storeId: 'store-lis-1',
    taxNumber: '228945102',
    socialSecurityNumber: '11456123098',
    email: 'pedro.compras@omniretail.pt',
    phone: '+351 925 789 123',
    baseSalary: 1450.00,
    mealAllowanceDaily: 9.60,
    contractType: 'sem_termo',
    admissionDate: '2023-01-10',
    status: 'ativo',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
];

export const initialTimeEntries: TimeClockEntry[] = [
  {
    id: 'tc-1',
    employeeId: 'emp-1',
    employeeName: 'Gonçalo Ribeiro',
    storeId: 'store-lis-1',
    date: '2026-08-23',
    clockIn: '08:55',
    lunchOut: '13:00',
    lunchIn: '14:00',
    clockOut: '',
    totalHours: 4.5,
    overtimeHours: 0,
    status: 'em_curso',
  },
  {
    id: 'tc-2',
    employeeId: 'emp-2',
    employeeName: 'Manuel Fernandes',
    storeId: 'store-lis-1',
    date: '2026-08-23',
    clockIn: '08:45',
    lunchOut: '13:15',
    lunchIn: '14:15',
    clockOut: '',
    totalHours: 4.8,
    overtimeHours: 0,
    status: 'em_curso',
  },
];

export const initialPayrolls: PayrollSlip[] = [
  {
    id: 'pay-1',
    companyId: 'comp-1',
    employeeId: 'emp-1',
    employeeName: 'Gonçalo Ribeiro',
    employeeRole: 'Operador de Caixa Senior',
    taxNumber: '249871230',
    monthYear: '07/2026',
    baseSalary: 1100.00,
    mealAllowance: 211.20, // 22 dias * 9.60
    overtimePay: 45.00,
    bonus: 50.00,
    grossTotal: 1406.20,
    socialSecurityDeduction: 121.00, // 11% sobre 1100
    irsRetention: 110.00, // 10%
    netSalary: 1175.20,
    companySocialSecurity: 261.25, // 23.75%
    totalEmployerCost: 1667.45,
    status: 'pago',
    paymentDate: '2026-07-28',
  },
  {
    id: 'pay-2',
    companyId: 'comp-1',
    employeeId: 'emp-2',
    employeeName: 'Manuel Fernandes',
    employeeRole: 'Gerente de Loja Lisboa',
    taxNumber: '210984561',
    monthYear: '07/2026',
    baseSalary: 1850.00,
    mealAllowance: 211.20,
    overtimePay: 0,
    bonus: 150.00,
    grossTotal: 2211.20,
    socialSecurityDeduction: 203.50,
    irsRetention: 314.50,
    netSalary: 1693.20,
    companySocialSecurity: 439.38,
    totalEmployerCost: 2650.58,
    status: 'pago',
    paymentDate: '2026-07-28',
  },
];

export const initialPurchaseRequisitions: PurchaseRequisition[] = [
  {
    id: 'req-1',
    companyId: 'comp-1',
    code: 'RC-2026-001',
    date: '2026-08-20',
    requesterId: 'usr-caixa',
    requesterName: 'Gonçalo Ribeiro',
    department: 'Loja Lisboa',
    priority: 'alta',
    status: 'aprovado',
    approvedBy: 'Manuel Fernandes',
    approvalDate: '2026-08-21',
    notes: 'Reposição urgente de Queijo da Serra e Fones ANC (stock crítico)',
    items: [
      { productId: 'prod-4', productName: 'Queijo da Serra Curado 500g', quantity: 25, estimatedUnitCost: 7.20, total: 180.00 },
      { productId: 'prod-5', productName: 'Auriculares Bluetooth Pro ANC', quantity: 15, estimatedUnitCost: 21.50, total: 322.50 },
    ],
    totalEstimated: 502.50,
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-1',
    companyId: 'comp-1',
    code: 'OC-2026-004',
    date: '2026-08-21',
    supplierId: 'sup-1',
    supplierName: 'Delta Cafés & Bebidas de Portugal S.A.',
    destinationWarehouseId: 'wh-lis-store',
    status: 'emitida',
    deliveryDateExpected: '2026-08-25',
    paymentTerms: '30 dias',
    items: [
      { productId: 'prod-1', productName: 'Café Espresso Gourmet 250g', quantityOrdered: 60, quantityReceived: 0, unitPrice: 2.20, taxRate: 13, total: 149.16 },
      { productId: 'prod-2', productName: 'Água Mineral das Pedras 6x25cl', quantityOrdered: 50, quantityReceived: 0, unitPrice: 1.65, taxRate: 6, total: 87.45 },
    ],
    subtotal: 214.50,
    taxTotal: 22.11,
    total: 236.61,
    notes: 'Entrega pela manhã nas traseiras da loja Baixa',
  },
];

export const initialLeads: LeadOpportunity[] = [
  {
    id: 'lead-1',
    companyId: 'comp-1',
    title: 'Fornecimento de Cafetaria Corporativa - BNP Paribas',
    contactName: 'Rui Albuquerque',
    companyName: 'BNP Paribas Sucursal Lisboa',
    email: 'rui.albuquerque@bnpparibas.com',
    phone: '+351 210 001 122',
    expectedValue: 14500.00,
    stage: 'negociacao',
    probability: 80,
    assignedTo: 'Manuel Fernandes',
    createdAt: '2026-08-01',
    nextFollowUp: '2026-08-25',
  },
  {
    id: 'lead-2',
    companyId: 'comp-1',
    title: 'Cabazes de Natal Empresariais 2026 (500 unidades)',
    contactName: 'Helena Matos',
    companyName: 'Deloitte Portugal',
    email: 'hmatos@deloitte.pt',
    phone: '+351 213 123 456',
    expectedValue: 35000.00,
    stage: 'proposta',
    probability: 60,
    assignedTo: 'Manuel Fernandes',
    createdAt: '2026-08-10',
    nextFollowUp: '2026-08-28',
  },
];

export const initialActiveShift: CashShift = {
  id: 'shift-1',
  companyId: 'comp-1',
  storeId: 'store-lis-1',
  terminalId: 'term-lis-1',
  operatorId: 'usr-caixa',
  operatorName: 'Gonçalo Ribeiro',
  openedAt: '2026-08-23T08:30:00Z',
  status: 'aberto',
  initialCash: 150.00, // 150€ fundo de maneio
  totalSales: 184.20,
  totalCash: 64.20,
  totalCards: 70.00,
  totalMbway: 50.00,
  totalTransfers: 0,
  totalVouchers: 0,
  sangriaTotal: 0,
  suprimentoTotal: 0,
  movements: [],
};

export const initialEvents: SystemEvent[] = [
  {
    id: 'evt-1',
    timestamp: '2026-08-23T08:30:00Z',
    service: 'POS',
    eventType: 'shift.opened',
    tenantId: 'comp-1',
    payload: { shiftId: 'shift-1', terminal: 'POS-01', operator: 'Gonçalo Ribeiro', initialCash: 150.00 },
    status: 'processed',
  },
  {
    id: 'evt-2',
    timestamp: '2026-08-23T09:15:22Z',
    service: 'POS',
    eventType: 'pos.sale.completed',
    tenantId: 'comp-1',
    payload: { invoiceNo: 'FS 2026/0001', total: 24.80, itemsCount: 3, paymentMethod: 'cartao' },
    status: 'processed',
  },
  {
    id: 'evt-3',
    timestamp: '2026-08-23T09:15:23Z',
    service: 'Stock',
    eventType: 'stock.decremented',
    tenantId: 'comp-1',
    payload: { warehouse: 'WH-LIS-01', itemsUpdated: 3, ref: 'FS 2026/0001' },
    status: 'processed',
  },
  {
    id: 'evt-4',
    timestamp: '2026-08-23T09:15:24Z',
    service: 'Financeiro',
    eventType: 'finance.ledger.posted',
    tenantId: 'comp-1',
    payload: { entryNo: 'LC-2026-089', debitTotal: 24.80, creditTotal: 24.80 },
    status: 'processed',
  },
  {
    id: 'evt-5',
    timestamp: '2026-08-23T09:15:25Z',
    service: 'CRM',
    eventType: 'crm.customer.points_earned',
    tenantId: 'comp-1',
    payload: { customerId: 'cust-2', pointsEarned: 24, newBalance: 480 },
    status: 'processed',
  },
];

export const initialOmnichannelOrders: OmnichannelOrder[] = [
  {
    id: 'ord-101',
    orderNumber: 'ENC-2026/089',
    channel: 'ecommerce',
    customerName: 'Manuel Ferreira',
    customerNif: '234567890',
    customerEmail: 'manuel.ferreira@empresa.pt',
    customerPhone: '+351 912 345 678',
    deliveryType: 'levantamento_loja',
    pickupStoreId: 'store-lis-1',
    items: [
      {
        productId: 'prod-4',
        productName: 'Azeite Virgem Extra DOP 500ml',
        sku: 'ALIM-004',
        quantity: 2,
        unitPrice: 8.50,
        total: 17.00,
      },
      {
        productId: 'prod-3',
        productName: 'Vinho Tinto Reserva Douro 75cl',
        sku: 'BEB-003',
        quantity: 1,
        unitPrice: 14.90,
        total: 14.90,
      },
    ],
    subtotal: 31.90,
    shippingFee: 0,
    total: 31.90,
    paymentMethod: 'mbway',
    paymentStatus: 'pago',
    status: 'pronto_levantamento',
    createdAt: '2026-08-23T08:15:00Z',
    notes: 'Cliente prefere levantamento entre as 12h e as 14h na loja de Lisboa Baixa.',
  },
  {
    id: 'ord-102',
    orderNumber: 'ENC-2026/090',
    channel: 'app_mobile',
    customerName: 'Beatriz Santos',
    customerNif: '245678901',
    customerEmail: 'beatriz.santos@email.pt',
    customerPhone: '+351 961 889 223',
    deliveryType: 'expresso_2h',
    deliveryAddress: 'Rua do Alecrim, 45, 2º Dto',
    deliveryCity: 'Lisboa',
    deliveryPostalCode: '1200-014',
    items: [
      {
        productId: 'prod-1',
        productName: 'Café Grão Arábica Premium 1kg',
        sku: 'ALIM-001',
        quantity: 1,
        unitPrice: 18.90,
        total: 18.90,
      },
      {
        productId: 'prod-2',
        productName: 'Chá Verde Orgânico 100g',
        sku: 'ALIM-002',
        quantity: 2,
        unitPrice: 4.50,
        total: 9.00,
      },
    ],
    subtotal: 27.90,
    shippingFee: 3.50,
    total: 31.40,
    paymentMethod: 'cartao',
    paymentStatus: 'pago',
    status: 'em_preparacao',
    createdAt: '2026-08-23T09:40:00Z',
    estimatedDelivery: '2026-08-23T11:40:00Z',
    notes: 'Entregar na portaria se ausente.',
  },
  {
    id: 'ord-103',
    orderNumber: 'ENC-2026/091',
    channel: 'click_collect',
    customerName: 'Inovação & Design Lda',
    customerNif: '508112233',
    customerEmail: 'compras@inovadesign.pt',
    customerPhone: '+351 210 556 778',
    deliveryType: 'levantamento_loja',
    pickupStoreId: 'store-por-2',
    items: [
      {
        productId: 'prod-5',
        productName: 'Queijo Serra da Estrela DOP 500g',
        sku: 'ALIM-005',
        quantity: 3,
        unitPrice: 16.50,
        total: 49.50,
      },
    ],
    subtotal: 49.50,
    shippingFee: 0,
    total: 49.50,
    paymentMethod: 'pagamento_na_loja',
    paymentStatus: 'pendente',
    status: 'pendente',
    createdAt: '2026-08-23T10:05:00Z',
    notes: 'Pagamento a efetuar no balcão no ato do levantamento em Porto Shopping.',
  },
];

export const initialBankTransactions: BankTransaction[] = [
  {
    id: 'tx-1',
    companyId: 'comp-1',
    date: '2026-08-22',
    description: 'TPA Terminal SIBS Lisboa Baixa',
    amount: 184.20,
    type: 'credito',
    reconciled: true,
    matchedEntityDoc: 'POS LIS-01',
  },
  {
    id: 'tx-2',
    companyId: 'comp-1',
    date: '2026-08-21',
    description: 'Transf. Cliente Arquitetos & Associados Lda',
    amount: 1240.00,
    type: 'credito',
    reconciled: true,
    matchedEntityDoc: 'FT 2026A/00140',
  },
  {
    id: 'tx-3',
    companyId: 'comp-1',
    date: '2026-08-20',
    description: 'Débito Direto EDP Comercial S.A. - Eletricidade',
    amount: 342.10,
    type: 'debito',
    reconciled: false,
    matchedEntityDoc: '',
  },
  {
    id: 'tx-4',
    companyId: 'comp-1',
    date: '2026-08-19',
    description: 'Pagamento Fornecedor Delta Cafés S.A.',
    amount: 870.00,
    type: 'debito',
    reconciled: true,
    matchedEntityDoc: 'FT-AGR-2026/1102',
  },
  {
    id: 'tx-5',
    companyId: 'comp-1',
    date: '2026-08-18',
    description: 'Comissão TPA SIBS Pagamentos',
    amount: 14.50,
    type: 'debito',
    reconciled: false,
    matchedEntityDoc: '',
  },
];

export const initialEmployeeShifts: EmployeeShift[] = [
  {
    id: 'sh-1',
    employeeId: 'emp-1',
    storeId: 'store-lis-1',
    date: '2026-08-23',
    startTime: '09:00',
    endTime: '18:00',
    breakDurationMinutes: 60,
    roleAssigned: 'Operador de Caixa (POS 1)',
    status: 'cumprido',
  },
  {
    id: 'sh-2',
    employeeId: 'emp-2',
    storeId: 'store-lis-1',
    date: '2026-08-23',
    startTime: '08:30',
    endTime: '17:30',
    breakDurationMinutes: 60,
    roleAssigned: 'Gerência e Abertura de Loja',
    status: 'cumprido',
  },
  {
    id: 'sh-3',
    employeeId: 'emp-4',
    storeId: 'store-lis-1',
    date: '2026-08-24',
    startTime: '08:00',
    endTime: '17:00',
    breakDurationMinutes: 60,
    roleAssigned: 'Receção de Cargas e Armazém',
    status: 'planeado',
  },
];

